install.packages("ggplot2")
install.packages("dplyr")
install.packages("magrittr")
install.packages("DiagrammeR")
install.packages("xaringan")
install.packages("miniUI")
install.packages("xaringanthemer")
install.packages("showtext")
install.packages("gtsummary")
install.packages("remotes")
remotes::install_github("gadenbuie/xaringanExtra")
remotes::install_github("gadenbuie/countdown")
remotes::install_github("mitchelloharawild/icon")
remotes::install_github("hadley/emo")
remotes::install_github("mitchelloharawild/icon", ref = remotes::github_release())
