install.packages("ggplot2")
install.packages("dplyr")
install.packages("purrr")
install.packages("magrittr")
install.packages("DiagrammeR")
install.packages("xaringan")
install.packages("miniUI")
install.packages("xaringanthemer")
install.packages("showtext")
install.packages("ggforce")
install.packages("gganimate")
install.packages("transformr")
install.packages("animation")
install.packages("gifski")
install.packages("cowplot")
install.packages("patchwork")
install.packages("palmerpenguins")
install.packages("gtsummary")
install.packages("remotes")
remotes::install_github("gadenbuie/xaringanExtra")
remotes::install_github("gadenbuie/countdown")
remotes::install_github("mitchelloharawild/icon")
remotes::install_github("hadley/emo")
remotes::install_github("mitchelloharawild/icon",  # or @v0.1.0
                        ref = remotes::github_release())
